### ISSUE TITLE
发现你的代码里面有问题，想联系了解一下。

### ISSUE THREAD

**Issue by youyoudong** [un4ckn0wl3z/un4ckn0wl3z#1]
从GitHub上检索到serverDemo项目（src/main/java/com/haoyun/commons/util/StringUtil.java）
的这个代码里面有问题，是否可以联系一下。因为没有其他联系方式，所以在此联系。

希望看到此发布内容，请于本人联系微信：269466146 或者 Email: zhouad@liandisys.com.cn

**Comment by un4ckn0wl3z** [comment]
@youyoudong check source code again please. 请再次检查源代码。
